### PR TITLE
Test/frozen package version

### LINKED ISSUE #1044: mpmath 1.4.0 breaks Frozen Applications due to importlib.metadata usage
## Summary
mpmath 1.4.0 breaks frozen applications (PyInstaller, py2app, cx_Freeze, Nuitka) by switching from hardcoded version strings to dynamic lookup via `importlib.metadata.version()`.

## Root Cause

**mpmath 1.4.0** ([`mpmath/__init__.py` L1-2](https://github.com/mpmath/mpmath/blob/master/mpmath/__init__.py#L1-L2)):
```python
from importlib.metadata import version
__version__ = version(__name__)
```

**Previous versions (1.2.1, 1.3.0)**:
```python
__version__ = '1.3.0'  # Hardcoded
```

**Problem**: Frozen applications bundle Python code but not package metadata (`.dist-info` directories), causing `importlib.metadata.version()` to fail with `PackageNotFoundError`.

## Minimal Reproduction

Simulate frozen app behavior without requiring PyInstaller:

```python
#!/usr/bin/env python3
"""Simulates frozen app behavior where package metadata is unavailable"""

import importlib.metadata

# Mock metadata to simulate frozen environment
original_version = importlib.metadata.version

def mock_version(package_name):
    if package_name == "mpmath":
        raise importlib.metadata.PackageNotFoundError(
            f"No package metadata was found for {package_name}"
        )
    return original_version(package_name)

importlib.metadata.version = mock_version

import mpmath  # ✗ FAILS on 1.4.0
print(f"mpmath version: {mpmath.__version__}")
```

## Workarounds

**Downgrade to mpmath 1.3.0:**
```bash
pip install mpmath==1.3.0
```
or in Poetry:
```toml
mpmath = "1.3.0"
```

## Proposed Solution

Use a fallback for when metadata is unavailable:

```python
try:
    from importlib.metadata import version
    __version__ = version(__name__)
except Exception:
    # Fallback for frozen apps or when metadata unavailable
    __version__ = "1.4.0"  # Update this string in each release
```

## Environment
- **mpmath**: 1.4.0
- **Python**: 3.10
  - expected on all 3.9+ versions supported by mpmath 1.4.0
- **Freezing tools**: PyInstaller 5.4.1
  - expected on all others also (py2app, cx_Freeze, Nuitka)
- **OS**: Windows

### PR DESCRIPTION
**Pull request by FlurinArner**
- Separate job to test the `pyinstaller` frozen application generation and `mpmath.__version__` availablity.
- Add bash script `mpmath/tests/test_version_frozen.sh`
- Ignore the `test_local/` folder generated in the `test_version_frozen.sh` bash script.
- Resolves the testing requirement for #1044

closes #1044

### CODE REVIEW

File: mpmath/tests/test_version_frozen.sh [hunk 1]
```diff
@@ -0,0 +1,66 @@
+#!/bin/bash
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh:1]: I think you are not using any bashisms.  Why not sh?

Please also add a small commentary here with brief description and point to issue number.

File: mpmath/tests/test_version_frozen.sh [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+set -e
+
+# Clean up any previous test artifacts
+echo "Cleaning up previous test artifacts..."
+rm -rf test_local build dist *.spec .venv
+
+mkdir -p test_local
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]: You can use mktemp utility to manage temporary directory outside of the mpmath tree.

File: mpmath/tests/test_version_frozen.sh [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+
+echo "Creating virtual environment..."
+python3 -m venv .venv
+source .venv/bin/activate
+
+
+cd .. # Leave the test_local directory to build the tarball from the local repo
+echo "Building tarball from local repo..."
+# Build the source distribution
+python3 -m pip install --quiet build
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]: Please install all deps here.  And please don't use ``--quiet`` and so on to silence output.

File: mpmath/tests/test_version_frozen.sh [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+
+
+# Create version_script.py that imports mpmath and prints the package version
+cat << EOF > version_script.py
+import mpmath
+print("mpmath version:", mpmath.__version__)
+EOF
+
+# Save version_script.py output to DIRECT_VERSION for later comparison
+DIRECT_VERSION=$(python version_script.py | grep "mpmath version:" | awk '{print $3}')
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]: You can get version by `python -m mpmath --version`.

File: mpmath/tests/test_version_frozen.sh [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+# Assert that the version from the frozen/bundled executable matches the direct version
+if [ "$DIRECT_VERSION" == "$FROZEN_VERSION" ]; then
+    echo "Test passed: Version matches in frozen (bundled) executable."
+else
+    echo "Test failed: Version mismatch."
+    echo "Direct version: $DIRECT_VERSION"
+    echo "Frozen version: $FROZEN_VERSION"
+    exit 1
+fi
+
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]:
```suggestion
```

File: .gitignore [hunk 6]
```diff
@@ -72,3 +72,6 @@ htmlcov/
 # per-project directories for virtual environments
 venv/
 .venv/
+
+# Temporary test directory
+test_local/
```
Comment (skirpichev) [inline .gitignore]: And this will be unnecessary with mktemp.

File: mpmath/tests/test_version_frozen.sh [hunk 7]
```diff
@@ -0,0 +1,66 @@
...
+python3 -m pip install --quiet build
+python3 -m build --sdist
+
+# Find and install the generated tarball
+TARBALL=$(ls -t dist/*.tar.gz | head -1)
+echo "Generated tarball: $TARBALL"
+
+# Install mpmath from the generated tarball
+echo "Installing mpmath from tarball..."
+pip install --quiet dist/"$(basename $TARBALL)"
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]: Don't be quiet here as well.

File: mpmath/tests/test_version_frozen.sh [hunk 8]
```diff
@@ -0,0 +1,66 @@
...
+echo "Building tarball from local repo..."
+# Build the source distribution
+python3 -m pip install --quiet build
+python3 -m build --sdist
+
+# Find and install the generated tarball
+TARBALL=$(ls -t dist/*.tar.gz | head -1)
+echo "Generated tarball: $TARBALL"
+
+# Install mpmath from the generated tarball
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]: This looks redundant.

File: mpmath/tests/test_version_frozen.sh [hunk 9]
```diff
@@ -0,0 +1,66 @@
...
+./dist/version_script 2>&1 | tee output.txt
+
+# Extract the version from the output
+FROZEN_VERSION=$(grep "mpmath version:" output.txt | awk '{print $3}')
+
+cd ..
+deactivate
+
+
+# Assert that the version from the frozen/bundled executable matches the direct version
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]:
```suggestion
```
Also useless.

File: mpmath/tests/test_version_frozen.sh [hunk 10]
```diff
@@ -0,0 +1,66 @@
...
+# Create version_script.py that imports mpmath and prints the package version
+cat << EOF > version_script.py
+import mpmath
+print("mpmath version:", mpmath.__version__)
+EOF
+
+# Save version_script.py output to DIRECT_VERSION for later comparison
+DIRECT_VERSION=$(python version_script.py | grep "mpmath version:" | awk '{print $3}')
+
+# Build with PyInstaller
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]: Redundant

File: mpmath/tests/test_version_frozen.sh [hunk 11]
```diff
@@ -0,0 +1,66 @@
...
+echo "Building version_script with PyInstaller..."
+pip install --quiet pyinstaller
+pyinstaller --onefile --clean version_script.py
+
+# Run the frozen executable and capture output
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]: Useless.

File: .github/workflows/test.yml [hunk 12]
```diff
@@ -12,6 +12,18 @@ jobs:
     uses: ./.github/workflows/coverage.yml
   docs:
     uses: ./.github/workflows/docs.yml
+  frozen-version:
+    runs-on: ubuntu-24.04
+    steps:
+    - uses: actions/checkout@v6
+      with:
+        fetch-depth: 0
+    - name: Set up Python (latest)
```
Comment (skirpichev) [inline .github/workflows/test.yml]: Latest stable.  I suggest just drop this name.  (Edit: I meant the "name" field.)

**Review by skirpichev — CHANGES_REQUESTED** [review]
Please see some comments.

Test is quick enough, so please also add it to the "needs" list of the tests job.

File: mpmath/tests/test_version_frozen.sh (hunk 8 above)
Comment (FlurinArner) [reply mpmath/tests/test_version_frozen.sh]: You mean just "the comment is redundant", correct?

Comment (skirpichev) [reply mpmath/tests/test_version_frozen.sh]: Yes.  Right below we see: "echo "Installing mpmath from tarball...""

File: mpmath/tests/test_version_frozen.sh (hunk 1 above)
Comment (FlurinArner) [reply mpmath/tests/test_version_frozen.sh:1]: I added a commentary, but actually the `source .venv/bin/activate` works only specifically with `bash`. 

There are alternatives for `fish` or `csh`, but I couldn't find how to get it to work in pure `sh`.

File: .github/workflows/test.yml (hunk 12 above)
Comment (FlurinArner) [reply .github/workflows/test.yml]: Let us try directly with `- uses: actions/setup-python@v6` then 👍

File: mpmath/tests/test_version_frozen.sh [hunk 13]
```diff
@@ -1,32 +1,38 @@
...
 echo "Cleaning up previous test artifacts..."
-rm -rf test_local build dist *.spec .venv
+rm -rf build dist *.spec .venv
 
-mkdir -p test_local
-cd test_local
+# Get the directory of the current repository
+MPMATH_DIR=$(pwd)
+# # Working directory independent version: 
+# MPMATH_DIR=$(realpath "$(dirname "$(realpath "$0")")/../..")
```
Comment (FlurinArner) [inline mpmath/tests/test_version_frozen.sh]: @skirpichev Let me know if you prefer the slighly complexer version (but safer), instead of using `pwd`

File: mpmath/tests/test_version_frozen.sh [hunk 14]
```diff
@@ -0,0 +1,67 @@
+#!/bin/bash
+# Test that the version number is provided correctly in a frozen (bundled) executable (see #1044).
+set -e
+
+# Clean up any previous test artifacts
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]:
```suggestion
```

File: mpmath/tests/test_version_frozen.sh [hunk 15]
```diff
@@ -0,0 +1,67 @@
...
+echo "Repo mpmath directory: $MPMATH_DIR"
+TEMP_DIR=$(mktemp -d)
+echo "Created temporary directory: $TEMP_DIR"
+cd "$TEMP_DIR"
+
+echo "Creating virtual environment..."
+python3 -m venv .venv
+source .venv/bin/activate
+
+
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]:
```suggestion
```

File: mpmath/tests/test_version_frozen.sh [hunk 16]
```diff
@@ -0,0 +1,67 @@
...
+cd "$MPMATH_DIR"
+echo "Building tarball from local repo..."
+# Build the source distribution
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]:
```suggestion
echo "Building the source distribution from local repo..."
```

File: mpmath/tests/test_version_frozen.sh [hunk 17]
```diff
@@ -0,0 +1,67 @@
...
+
+# Find and install the generated tarball
+TARBALL=$(ls -t dist/*.tar.gz | head -1)
+echo "Generated tarball: $TARBALL"
+
+echo "Installing mpmath from tarball..."
+pip install dist/"$(basename $TARBALL)"
+cd "$TEMP_DIR" # Return to temporary folder to run the version script
+
+
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]:
```suggestion
```

File: mpmath/tests/test_version_frozen.sh [hunk 18]
```diff
@@ -0,0 +1,67 @@
...
+# Create version_script.py that imports mpmath and prints the package version
+cat << EOF > version_script.py
+import mpmath
+print("mpmath version:", mpmath.__version__)
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]:
```suggestion
print(mpmath.__version__)
```

File: mpmath/tests/test_version_frozen.sh [hunk 19]
```diff
@@ -0,0 +1,67 @@
...
+set -e
+
+# Clean up any previous test artifacts
+echo "Cleaning up previous test artifacts..."
+rm -rf build dist *.spec .venv
+
+# Get the directory of the current repository
+MPMATH_DIR=$(pwd)
+# # Working directory independent version: 
+# MPMATH_DIR=$(realpath "$(dirname "$(realpath "$0")")/../..")
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]: Assuming bash, you can use pushd/popd and get rid of this variable.  Though, I don't see why you need one.

File: mpmath/tests/test_version_frozen.sh [hunk 20]
```diff
@@ -0,0 +1,67 @@
...
+DIRECT_VERSION=$(python -m mpmath --version)
+
+echo "Building version_script with PyInstaller..."
+pyinstaller --onefile --clean version_script.py
+
+echo "Running frozen executable..."
+./dist/version_script 2>&1 | tee output.txt
+
+# Extract the version from the output
+FROZEN_VERSION=$(grep "mpmath version:" output.txt | awk '{print $3}')
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]:
```suggestion
echo "Run frozen executable and extract the version from the output"
FROZEN_VERSION=$(./dist/version_script 2>&1)
```

File: mpmath/tests/test_version_frozen.sh [hunk 21]
```diff
@@ -0,0 +1,67 @@
...
+
+# Return to the original repository directory
+cd "$MPMATH_DIR" 
+deactivate
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]: In principle, it's useless.

File: mpmath/tests/test_version_frozen.sh [hunk 22]
```diff
@@ -0,0 +1,67 @@
+#!/bin/bash
+# Test that the version number is provided correctly in a frozen (bundled) executable (see #1044).
+set -e
+
+# Clean up any previous test artifacts
+echo "Cleaning up previous test artifacts..."
+rm -rf build dist *.spec .venv
```
Comment (skirpichev) [inline mpmath/tests/test_version_frozen.sh]: *.spec ?

File: mpmath/tests/test_version_frozen.sh (hunk 13 above)
Comment (skirpichev) [reply mpmath/tests/test_version_frozen.sh]: You are right, this version is better.  But I don't think you need a separate variable for this.

File: mpmath/tests/test_version_frozen.sh (hunk 22 above)
Comment (FlurinArner) [reply mpmath/tests/test_version_frozen.sh]: Ah, this is also from `pyinstaller` and was in the `temp_folder`.. Actually this didn't work, since it was generated inside that folder.

Removed

File: mpmath/tests/test_version_frozen.sh (hunk 13 above)
Comment (FlurinArner) [reply mpmath/tests/test_version_frozen.sh]: I kept the `MPMATH_DIR` variable definition, because `realpath $0` returns `No such file or directory` after performing a `cd` to a different directory.

File: mpmath/tests/test_version_frozen.sh (hunk 21 above)
Comment (FlurinArner) [reply mpmath/tests/test_version_frozen.sh]: Ah, you're saying here that I should remove `deactivate`, because nobody will be using the script in a manual way and the shell session will be closed once the test completes?

**Review by skirpichev — APPROVED** [review]
I did some final edits, instead of trying to do yet another review turn, sorry.

Now looks good for me.

**Comment by FlurinArner** [comment]
> I did some final edits, instead of trying to do yet another review turn, sorry.

That's good for me! Thanks for the positive feedback and quick resolution. 

Just to be sure (since [you moved](https://github.com/mpmath/mpmath/pull/1055/changes/54f2aa705fb06f3d2919017634614b3a03e5d3ec#diff-2688cec3c1b113e004a5f57e3104f1fbe1768cbd6bff9c5d32daf7b96d95a00eR25) the `venv` creation and activation to **after** installing the tarball), I re-tested the `test_version_frozen.sh` against `v1.4.0` and can confirm that it would have failed. Now on `master` (after #1048) the test succeeds. :+1:
